#!/usr/bin/env python3
"""
Q=550 relative-defect micro-box pilot for the frozen-spline cocycle.

This pilot addresses the two failure modes isolated in the previous interval
attempts:

1. A requested microinterval is enclosed with the cubic spline restricted to
   that exact microinterval.  It is never replaced by the box of the complete
   spline segment.

2. Each local transition is validated in a moving frame.  If U(t) is the
   cubic-Hermite approximate local fundamental matrix and

       R = U' - B U,
       X = U (I + E),

   then

       E' = -U^{-1} R (I + E).

   The large rotational part of B therefore disappears from the error-growth
   equation.  On each residual subcell we bound U^{-1} by a Neumann estimate
   around the identity and integrate ||U^{-1}R||.

The script validates one selected dense start only.  Its purpose is to decide
whether this proof architecture produces useful radii before scaling it to all
81 starts.  Scope is still the linear cocycle generated by the frozen natural
cubic spline reconstructed from the archived orbit; the nonlinear orbit cache
is not yet validated against an exact trajectory.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, Iterable

import mpmath as mp
import numpy as np


SCRIPT_VERSION = "2026-08-07-q550-relative-defect-microbox-pilot-v1.4-knot-touch-fix"
DEFAULT_BASE = Path("test_support_q550_interval_spline_cocycle_proof.py")
DEFAULT_DENSE_RAW = Path("support_q550_dense_start_span_closure_raw.npz")
DEFAULT_AUDIT = Path("test_support_mobius_monodromy_audit.py")
DEFAULT_ORBIT = Path("support_feedback_q_curtain_cache/q_550_orbit.npz")
DEFAULT_OUTPUT = Path("support_q550_relative_defect_microbox_pilot")


@dataclass
class LocalValidatedTransport:
    center: np.ndarray
    radius: float
    steps: int
    residual_subdivisions: int
    maximum_microbox_width: float
    maximum_path_distance_from_identity: float
    maximum_relative_defect_rate: float
    accumulated_relative_defect: float
    maximum_local_relative_error: float
    maximum_local_absolute_radius: float
    microbox_cache_size: int


def load_module(path: Path, name: str) -> ModuleType:
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(f"Required script not found: {path}")
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def require_attributes(module: ModuleType, names: Iterable[str], label: str) -> None:
    missing = [name for name in names if not hasattr(module, name)]
    if missing:
        raise AttributeError(f"{label} is missing: " + ", ".join(missing))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def outward(value: float) -> float:
    return float(np.nextafter(float(value), np.inf))


def box_spectral_upper(base: ModuleType, box: Any) -> float:
    """Upper bound ||A||_2 <= sqrt(||A||_1 ||A||_inf) for A in box."""
    absolute = np.asarray(base.box_abs_upper(box), dtype=float)
    one = outward(float(np.max(np.sum(absolute, axis=0))))
    infinity = outward(float(np.max(np.sum(absolute, axis=1))))
    with mp.workdps(base.MP_DPS):
        value = mp.sqrt(mp.mpf(one) * mp.mpf(infinity))
        _, high = base.mp_bracket(value, ulps=4)
    return float(high)


def box_width_max(box: Any) -> float:
    return float(np.max(np.asarray(box.hi, dtype=float) - np.asarray(box.lo, dtype=float)))


class LocalCubicGeneratorEnvelope:
    """Outward-rounded generator enclosure on the exact requested interval.

    Unlike the coarse envelope used by the first interval attempt, ``box(a, b)``
    restricts every cubic-spline segment to the actual overlap with ``[a, b]``.
    This preserves the small generator variation on residual microcells.
    """

    def __init__(
        self,
        base: ModuleType,
        audit: ModuleType,
        spline: Any,
        knots: np.ndarray,
        *,
        domain_left: float,
        domain_right: float,
        kappa0: float,
        params: Any,
        basis: np.ndarray,
        basis_box: Any,
        left_matrix: np.ndarray,
        left_box: Any,
    ) -> None:
        self.base = base
        self.audit = audit
        self.spline = spline
        self.knots = np.asarray(knots, dtype=float)
        self.domain_left = float(domain_left)
        self.domain_right = float(domain_right)
        self.kappa0 = float(kappa0)
        self.params = params
        self.basis = np.asarray(basis, dtype=float)
        self.basis_box = basis_box
        self.left_matrix = np.asarray(left_matrix, dtype=float)
        self.left_box = left_box

        extraction = np.asarray(audit.reduced_extraction(), dtype=float)
        embedding = np.asarray(audit.reduced_embedding("symmetric"), dtype=float)
        self.extraction_box = base.constant_matrix_box(
            extraction, exact_zero_one=True
        )
        self.embedding_box = base.constant_matrix_box(
            embedding, exact_zero_one=True
        )
        self._cache: dict[tuple[float, float], Any] = {}

        if self.knots.ndim != 1 or self.knots.size < 2:
            raise ValueError("Invalid spline knot vector")
        if not self.domain_left < self.domain_right:
            raise ValueError("Invalid generator-envelope domain")

        tolerance = 128.0 * np.finfo(float).eps * max(
            abs(self.domain_left), abs(self.domain_right), 1.0
        )
        if self.domain_left < self.knots[0] - tolerance:
            raise ValueError("Generator domain starts below spline domain")
        if self.domain_right > self.knots[-1] + tolerance:
            raise ValueError("Generator domain ends above spline domain")

    @property
    def cache_size(self) -> int:
        return len(self._cache)

    def point(self, value: float) -> np.ndarray:
        value = float(value)
        tolerance = 128.0 * np.finfo(float).eps * max(
            abs(self.domain_left), abs(self.domain_right), 1.0
        )
        if value < self.domain_left - tolerance or value > self.domain_right + tolerance:
            raise ValueError(f"Generator point {value:.17g} outside pilot domain")
        state = np.asarray(self.spline(value), dtype=float)
        raw = np.asarray(
            self.audit.reduced_jacobian_rotation(
                state, kappa0=self.kappa0, params=self.params
            ),
            dtype=float,
        )
        transformed = self.left_matrix @ raw @ self.basis
        if transformed.shape != (9, 9) or not np.all(np.isfinite(transformed)):
            raise FloatingPointError("Invalid point generator")
        return transformed

    def box(self, left: float, right: float) -> Any:
        left = float(left)
        right = float(right)
        if right < left:
            left, right = right, left

        tolerance = 128.0 * np.finfo(float).eps * max(
            abs(self.domain_left), abs(self.domain_right), abs(left), abs(right), 1.0
        )
        if left < self.domain_left - tolerance:
            raise ValueError("Generator interval below pilot domain")
        if right > self.domain_right + tolerance:
            raise ValueError("Generator interval above pilot domain")

        left = max(left, self.domain_left)
        right = min(right, self.domain_right)
        key = (left, right)
        cached = self._cache.get(key)
        if cached is not None:
            return cached

        first = max(
            0, int(np.searchsorted(self.knots, left, side="right") - 1)
        )
        last = min(
            self.knots.size - 2,
            int(np.searchsorted(self.knots, right, side="left")),
        )

        boxes: list[Any] = []
        for index in range(first, last + 1):
            knot_left = float(self.knots[index])
            knot_right = float(self.knots[index + 1])
            segment_left = max(left, knot_left)
            segment_right = min(right, knot_right)
            # A segment selected by searchsorted can be a floating-point
            # near-touch with no actual overlap.  The old tolerance test kept
            # such a segment when 0 < segment_left-segment_right <= tolerance,
            # which then produced dx_left > dx_right and an invalid Box.
            # If the floating endpoints are ordered as an empty intersection,
            # skip it unconditionally; any true knot contact is represented by
            # the adjacent segment with segment_left <= segment_right.
            if segment_right < segment_left:
                continue

            dx_left = max(0.0, segment_left - knot_left)
            dx_right = min(knot_right - knot_left, segment_right - knot_left)
            coefficients = np.asarray(self.spline.c[:, index, :], dtype=float)
            state_box = self.base.interval_cubic(
                coefficients, dx_left, dx_right
            )
            generator_box = self.base.reduced_rotation_generator_interval(
                state_box,
                kappa0=self.kappa0,
                params=self.params,
                extraction_box=self.extraction_box,
                embedding_box=self.embedding_box,
                left_box=self.left_box,
                basis_box=self.basis_box,
            )
            boxes.append(generator_box)

        if not boxes:
            raise RuntimeError(
                f"No spline segment overlaps [{left:.17g}, {right:.17g}]"
            )
        result = self.base.hull(boxes)
        self._cache[key] = result
        return result


def hermite_path_box(
    base: ModuleType,
    y0: np.ndarray,
    y1: np.ndarray,
    f0: np.ndarray,
    f1: np.ndarray,
    step: float,
    *,
    tau_left: float,
    tau_right: float,
) -> Any:
    a0 = y0
    a1 = step * f0
    a2 = -3.0 * y0 - 2.0 * step * f0 + 3.0 * y1 - step * f1
    a3 = 2.0 * y0 + step * f0 - 2.0 * y1 + step * f1
    tau = base.Box(np.asarray(float(tau_left)), np.asarray(float(tau_right)))
    return base.polynomial_box([a0, a1, a2, a3], tau)

def hermite_derivative_box(
    base: ModuleType,
    y0: np.ndarray,
    y1: np.ndarray,
    f0: np.ndarray,
    f1: np.ndarray,
    step: float,
    *,
    tau_left: float,
    tau_right: float,
) -> Any:
    a1 = step * f0
    a2 = -3.0 * y0 - 2.0 * step * f0 + 3.0 * y1 - step * f1
    a3 = 2.0 * y0 + step * f0 - 2.0 * y1 + step * f1
    tau = base.Box(np.asarray(float(tau_left)), np.asarray(float(tau_right)))
    derivative_tau = base.polynomial_box([a1, 2.0 * a2, 3.0 * a3], tau)
    return base.iscale(derivative_tau, 1.0 / step)


def hermite_derivative_value(
    y0: np.ndarray,
    y1: np.ndarray,
    f0: np.ndarray,
    f1: np.ndarray,
    step: float,
    tau: float,
) -> np.ndarray:
    a1 = step * f0
    a2 = -3.0 * y0 - 2.0 * step * f0 + 3.0 * y1 - step * f1
    a3 = 2.0 * y0 + step * f0 - 2.0 * y1 + step * f1
    return (a1 + 2.0 * a2 * tau + 3.0 * a3 * tau * tau) / step


def centered_hermite_residual_box(
    base: ModuleType,
    y0: np.ndarray,
    y1: np.ndarray,
    f0: np.ndarray,
    f1: np.ndarray,
    step: float,
    generator_box: Any,
    generator_midpoint: np.ndarray,
    path_box: Any,
    *,
    tau_left: float,
    tau_right: float,
) -> Any:
    """Cancellation-preserving enclosure of U' - B U.

    Freeze B at the microinterval midpoint B_c.  Because U is cubic Hermite,
    U' - B_c U is a cubic matrix polynomial whose coefficients can be formed
    before interval evaluation.  The remaining generator variation enters as

        -(B-B_c) U,

    and is small on the exact microinterval.
    """
    a0 = y0
    a1 = step * f0
    a2 = -3.0 * y0 - 2.0 * step * f0 + 3.0 * y1 - step * f1
    a3 = 2.0 * y0 + step * f0 - 2.0 * y1 + step * f1

    residual_coefficients = [
        a1 / step - generator_midpoint @ a0,
        2.0 * a2 / step - generator_midpoint @ a1,
        3.0 * a3 / step - generator_midpoint @ a2,
        -generator_midpoint @ a3,
    ]
    tau = base.Box(np.asarray(float(tau_left)), np.asarray(float(tau_right)))
    frozen_residual = base.polynomial_box(residual_coefficients, tau)
    generator_variation = base.isub(
        generator_box, base.exact_box(generator_midpoint)
    )
    return base.isub(
        frozen_residual,
        base.imatmul(generator_variation, path_box),
    )


def hermite_path_value(
    y0: np.ndarray,
    y1: np.ndarray,
    f0: np.ndarray,
    f1: np.ndarray,
    step: float,
    tau: float,
) -> np.ndarray:
    a0 = y0
    a1 = step * f0
    a2 = -3.0 * y0 - 2.0 * step * f0 + 3.0 * y1 - step * f1
    a3 = 2.0 * y0 + step * f0 - 2.0 * y1 + step * f1
    return ((a3 * tau + a2) * tau + a1) * tau + a0


def inverse_path_upper(
    base: ModuleType,
    path_box: Any,
    path_midpoint: np.ndarray,
) -> tuple[float, float]:
    """Banach-lemma bound for every U in path_box.

    With a numerical approximate inverse V of the midpoint path,

        ||I - V U||_2 <= eta < 1

    implies

        ||U^{-1}||_2 <= ||V||_2 / (1-eta).

    All products involving the varying U are evaluated with outward-rounded
    interval arithmetic.
    """
    approximate_inverse = np.linalg.inv(path_midpoint)
    inverse_box = base.float_box(approximate_inverse, ulps=6)
    product_box = base.imatmul(inverse_box, path_box)
    identity_box = base.constant_matrix_box(np.eye(9), exact_zero_one=True)
    residual_box = base.isub(product_box, identity_box)
    eta = box_spectral_upper(base, residual_box)
    if not eta < 1.0:
        raise FloatingPointError(
            f"Banach inverse failed: ||I-VU||_2 <= {eta:.6e}"
        )
    inverse_norm = box_spectral_upper(base, inverse_box)
    return outward(inverse_norm / (1.0 - eta)), eta


def validate_transport_relative_defect(
    base: ModuleType,
    envelope: LocalCubicGeneratorEnvelope,
    *,
    start: float,
    step: float,
    steps: int,
    residual_subdivisions: int,
    label: str,
) -> LocalValidatedTransport:
    if steps < 1:
        raise ValueError("steps must be positive")
    if residual_subdivisions < 1:
        raise ValueError("residual_subdivisions must be positive")

    center = np.eye(9, dtype=float)
    relative_error = 0.0

    maximum_microbox_width = 0.0
    maximum_path_inverse_test = 0.0
    maximum_defect_rate = 0.0
    accumulated_defect = 0.0
    maximum_local_relative = 0.0
    maximum_local_absolute = 0.0

    progress_every = max(1, steps // 10)
    for index in range(steps):
        s0 = start + index * step
        sm = s0 + 0.5 * step
        s1 = s0 + step
        b0 = envelope.point(s0)
        bm = envelope.point(sm)
        b1 = envelope.point(s1)

        y0 = center
        k1 = b0 @ y0
        k2 = bm @ (y0 + 0.5 * step * k1)
        k3 = bm @ (y0 + 0.5 * step * k2)
        k4 = b1 @ (y0 + step * k3)
        y1 = y0 + (step / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
        f0 = b0 @ y0
        f1 = b1 @ y1

        local_integral = 0.0
        for subdivision in range(residual_subdivisions):
            tau_left = subdivision / residual_subdivisions
            tau_right = (subdivision + 1) / residual_subdivisions
            tau_middle = 0.5 * (tau_left + tau_right)
            sub_left = s0 + tau_left * step
            sub_right = s0 + tau_right * step

            generator_box = envelope.box(sub_left, sub_right)
            path_box = hermite_path_box(
                base,
                y0,
                y1,
                f0,
                f1,
                step,
                tau_left=tau_left,
                tau_right=tau_right,
            )
            path_midpoint = hermite_path_value(
                y0, y1, f0, f1, step, tau_middle
            )
            generator_midpoint = envelope.point(s0 + tau_middle * step)
            residual_box = centered_hermite_residual_box(
                base,
                y0,
                y1,
                f0,
                f1,
                step,
                generator_box,
                generator_midpoint,
                path_box,
                tau_left=tau_left,
                tau_right=tau_right,
            )

            inverse_upper, inverse_test = inverse_path_upper(
                base, path_box, path_midpoint
            )
            residual_upper = base.box_frobenius_upper(residual_box)
            defect_rate = outward(inverse_upper * residual_upper)
            substep = step * (tau_right - tau_left)
            local_integral = outward(local_integral + defect_rate * substep)

            maximum_microbox_width = max(
                maximum_microbox_width, box_width_max(generator_box)
            )
            maximum_path_inverse_test = max(
                maximum_path_inverse_test, inverse_test
            )
            maximum_defect_rate = max(maximum_defect_rate, defect_rate)

        with mp.workdps(base.MP_DPS):
            growth = mp.exp(mp.mpf(local_integral))
            next_relative = growth * (1 + mp.mpf(relative_error)) - 1
            local_relative = mp.expm1(mp.mpf(local_integral))
            _, next_high = base.mp_bracket(next_relative, ulps=4)
            _, local_high = base.mp_bracket(local_relative, ulps=4)
        relative_error = float(next_high)
        local_relative_float = float(local_high)
        center = y1

        center_norm = box_spectral_upper(base, base.float_box(center, ulps=6))
        local_absolute = outward(center_norm * local_relative_float)
        accumulated_defect = outward(accumulated_defect + local_integral)
        maximum_local_relative = max(
            maximum_local_relative, local_relative_float
        )
        maximum_local_absolute = max(maximum_local_absolute, local_absolute)

        if index == 0 or index + 1 == steps or (index + 1) % progress_every == 0:
            current_radius = outward(center_norm * relative_error)
            print(
                f"    {label}: [{index + 1:>5}/{steps}] "
                f"radius={current_radius:.3e} microboxes={int(getattr(envelope, "cache_size", 0))}",
                flush=True,
            )

    final_norm = box_spectral_upper(base, base.float_box(center, ulps=6))
    radius = outward(final_norm * relative_error)
    return LocalValidatedTransport(
        center=center,
        radius=radius,
        steps=steps,
        residual_subdivisions=residual_subdivisions,
        maximum_microbox_width=maximum_microbox_width,
        maximum_path_distance_from_identity=maximum_path_inverse_test,
        maximum_relative_defect_rate=maximum_defect_rate,
        accumulated_relative_defect=accumulated_defect,
        maximum_local_relative_error=maximum_local_relative,
        maximum_local_absolute_radius=maximum_local_absolute,
        microbox_cache_size=int(getattr(envelope, "cache_size", 0)),
    )

def relative_matrix_difference(a: np.ndarray, b: np.ndarray) -> float:
    denominator = max(
        float(np.linalg.norm(a, ord="fro")),
        float(np.linalg.norm(b, ord="fro")),
        1e-300,
    )
    return float(np.linalg.norm(a - b, ord="fro") / denominator)


def write_report(path: Path, payload: dict[str, Any]) -> None:
    transports = payload["transports"]
    structural = payload["structural"]
    lines = [
        f"Script version: {payload['script_version']}",
        "",
        "Q=550 RELATIVE-DEFECT MICRO-BOX PILOT",
        "======================================",
        "",
        f"scope                              = {payload['scope']}",
        f"dense raw                          = {payload['dense_raw']}",
        f"orbit cache                        = {payload['orbit']}",
        f"selected center index              = {payload['center_index']}",
        f"selected start                     = {payload['start']:.15f}",
        f"P_line                            = {payload['p_line']:.15f}",
        f"P_oriented                        = {payload['p_oriented']:.15f}",
        f"common step                        = {payload['common_step']:.15e}",
        f"steps per P_line                  = {payload['steps_per_line']}",
        f"residual subdivisions             = {payload['residual_subdivisions']}",
        "",
        "Validated transport radii",
        "---------------------------",
    ]
    for name in ("line", "second", "oriented", "two_line"):
        row = transports[name]
        lines.extend(
            [
                f"{name}",
                f"  steps                            = {row['steps']}",
                f"  radius                           = {row['radius']:.12e}",
                f"  archived relative discrepancy   = {row['archived_relative_discrepancy']:.12e}",
                f"  max micro generator width       = {row['maximum_microbox_width']:.12e}",
                f"  max Banach inverse residual             = {row['maximum_path_distance_from_identity']:.12e}",
                f"  max relative defect rate        = {row['maximum_relative_defect_rate']:.12e}",
                f"  accumulated relative defect     = {row['accumulated_relative_defect']:.12e}",
                f"  max local relative error        = {row['maximum_local_relative_error']:.12e}",
                f"  max local absolute radius       = {row['maximum_local_absolute_radius']:.12e}",
            ]
        )
    lines.extend(
        [
            "",
            "Structural lower bounds at the selected center",
            "------------------------------------------------",
            f"active determinant center          = {structural['active_det_center']:+.12e}",
            f"active sigma lower                 = {structural['active_sigma_lower']:+.12e}",
            f"without-z determinant center       = {structural['without_z_det_center']:+.12e}",
            f"without-z sigma lower              = {structural['without_z_sigma_lower']:+.12e}",
            f"mediation margin lower             = {structural['mediation_margin_lower']:+.12e}",
            f"endpoint separation lower          = {structural['endpoint_separation_lower']:+.12e}",
            f"composition enclosure upper        = {structural['composition_enclosure_upper']:.12e}",
            "",
            "Decisions",
            "---------",
            f"active orientation passed          = {structural['active_orientation_pass']}",
            f"without-z orientation passed       = {structural['without_z_orientation_pass']}",
            f"mediation passed                   = {structural['mediation_pass']}",
            f"endpoint separation passed         = {structural['endpoint_separation_pass']}",
            f"all structural passed              = {structural['all_structural_pass']}",
            f"pilot target passed                = {payload['pilot_target_passed']}",
            f"classification                     = {payload['classification']}",
            "",
            "Interpretation",
            "--------------",
            "This pilot validates one frozen-spline start.  A pass shows that exact",
            "microinterval boxes plus a moving-frame relative defect can produce",
            "radii small enough for the structural margins.  It does not yet cover",
            "all 81 starts or validate the archived nonlinear orbit.",
        ]
    )
    path.write_text("\n".join(lines) + "\n")


def run_self_test(base: ModuleType) -> None:
    rng = np.random.default_rng(20260806)
    raw = rng.normal(size=(9, 9))
    skew = 20.0 * (raw - raw.T) / max(np.linalg.norm(raw - raw.T, ord=2), 1e-15)
    generator = skew - 0.03 * np.eye(9)

    class ConstantEnvelope:
        def __init__(self) -> None:
            self.cache: dict[Any, Any] = {}

        def point(self, value: float) -> np.ndarray:
            del value
            return generator

        def box(self, left: float, right: float) -> Any:
            key = (float(left).hex(), float(right).hex())
            if key not in self.cache:
                self.cache[key] = base.float_box(generator, ulps=4)
            return self.cache[key]

    length = 0.37
    steps = 240
    result = validate_transport_relative_defect(
        base,
        ConstantEnvelope(),
        start=0.0,
        step=length / steps,
        steps=steps,
        residual_subdivisions=4,
        label="self-test",
    )
    exact = base.expm(generator * length)
    actual = float(np.linalg.norm(result.center - exact, ord="fro"))
    if actual > result.radius:
        raise AssertionError(
            f"relative-defect self-test escaped enclosure: {actual:.3e} > {result.radius:.3e}"
        )
    print(
        "relative-defect self-test passed: "
        f"actual={actual:.3e}, radius={result.radius:.3e}, "
        f"max inverse residual={result.maximum_path_distance_from_identity:.3e}",
        flush=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Pilot exact micro-spline boxes and moving-frame relative-defect validation at one Q=550 dense start."
    )
    parser.add_argument("--base-script", type=Path, default=DEFAULT_BASE)
    parser.add_argument("--dense-raw", type=Path, default=DEFAULT_DENSE_RAW)
    parser.add_argument("--audit-script", type=Path, default=DEFAULT_AUDIT)
    parser.add_argument("--orbit", type=Path, default=DEFAULT_ORBIT)
    parser.add_argument("--q", type=float, default=550.0)
    parser.add_argument("--center-index", type=int, default=67)
    parser.add_argument("--steps-per-line", type=int, default=656)
    parser.add_argument("--residual-subdivisions", type=int, default=4)
    parser.add_argument("--gamma-rho", type=float, default=0.3)
    parser.add_argument("--tail-periods", type=int, default=70)
    parser.add_argument("--steps-per-period", type=int, default=160)
    parser.add_argument("--samples-per-rotation", type=int, default=720)
    parser.add_argument("--initial-x-perturbation", type=float, default=1e-6)
    parser.add_argument("--mp-dps", type=int, default=80)
    parser.add_argument("--planar-failure-threshold", type=float, default=0.95)
    parser.add_argument("--target-radius", type=float, default=3e-3)
    parser.add_argument("--output-prefix", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.steps_per_line < 20:
        parser.error("--steps-per-line must be at least 20")
    if args.residual_subdivisions < 1:
        parser.error("--residual-subdivisions must be positive")
    if args.mp_dps < 50:
        parser.error("--mp-dps must be at least 50")
    if not (0.0 < args.planar_failure_threshold < 1.0):
        parser.error("--planar-failure-threshold must lie in (0,1)")

    base = load_module(args.base_script, "relative_defect_microbox_base")
    base.MP_DPS = int(args.mp_dps)
    require_attributes(
        base,
        (
            "Box",
            "float_box",
            "exact_box",
            "constant_matrix_box",
            "interval_cubic",
            "reduced_rotation_generator_interval",
            "polynomial_box",
            "hermite_residual_box",
            "box_abs_upper",
            "box_frobenius_upper",
            "imatmul",
            "isub",
            "iadd",
            "iscale",
            "hull",
            "mp_bracket",
            "mp_inverse_enclosure",
            "structural_bounds",
            "expm",
        ),
        "base interval script",
    )

    if args.self_test:
        run_self_test(base)
        return

    for path, label in (
        (args.dense_raw, "dense raw"),
        (args.audit_script, "audit script"),
        (args.orbit, "orbit cache"),
    ):
        if not path.exists():
            parser.error(f"{label} not found: {path}")

    audit = load_module(args.audit_script, "relative_defect_microbox_audit")
    require_attributes(
        audit,
        (
            "ModelParameters",
            "load_orbit",
            "collect_uniform_tail",
            "build_state_spline",
            "reduced_jacobian_rotation",
            "reduced_extraction",
            "reduced_embedding",
            "full_jacobian",
        ),
        "audit script",
    )

    with np.load(args.dense_raw, allow_pickle=True) as raw:
        q_stored = float(raw["q"])
        if not math.isclose(q_stored, args.q, rel_tol=0.0, abs_tol=1e-10):
            raise ValueError(f"Dense raw Q={q_stored:g}, requested Q={args.q:g}")
        starts = np.asarray(raw["starts"], dtype=float)
        if not (0 <= args.center_index < starts.size):
            parser.error(f"--center-index must lie in [0,{starts.size - 1}]")
        p_line = float(raw["p_line"])
        p_oriented = float(raw["p_oriented"])
        basis = np.asarray(raw["basis"], dtype=float)
        labels = [str(value) for value in raw["basis_labels"]]
        archived = {
            "line": np.asarray(raw["fine_line"], dtype=float)[args.center_index],
            "second": np.asarray(raw["fine_second"], dtype=float)[args.center_index],
            "oriented": np.asarray(raw["fine_oriented"], dtype=float)[args.center_index],
            "two_line": np.asarray(raw["fine_two_line"], dtype=float)[args.center_index],
        }

    if labels[:2] != ["lower angular bascule", "upper counterbalance"]:
        raise RuntimeError("Unexpected active basis ordering")
    if "upper z residual" not in labels:
        raise RuntimeError("upper z residual basis label missing")
    z_index = labels.index("upper z residual")

    start = float(starts[args.center_index])
    second_length = p_oriented - p_line
    common_step = p_line / args.steps_per_line
    lengths = {
        "line": p_line,
        "second": second_length,
        "oriented": p_oriented,
        "two_line": 2.0 * p_line,
    }
    step_counts = {name: int(round(length / common_step)) for name, length in lengths.items()}
    for name, length in lengths.items():
        represented = step_counts[name] * common_step
        tolerance = 128.0 * np.finfo(float).eps * max(abs(length), 1.0)
        if abs(represented - length) > tolerance:
            raise RuntimeError(
                f"Common step does not represent {name} exactly enough: "
                f"{represented:.17g} vs {length:.17g}. Choose another --steps-per-line."
            )

    print(f"Script version       = {SCRIPT_VERSION}")
    print(f"selected center      = {args.center_index}/{starts.size - 1}")
    print(f"selected start       = {start:.15f}")
    print(f"steps per P_line     = {args.steps_per_line}")
    print(f"common step          = {common_step:.15e}")
    print(f"step counts          = {step_counts}")
    print(f"residual subdivisions= {args.residual_subdivisions}")
    print(f"mp.dps               = {args.mp_dps}")

    params = audit.ModelParameters(gamma_rho=args.gamma_rho)
    orbit = audit.load_orbit(args.q, args.orbit)
    tail = audit.collect_uniform_tail(
        orbit,
        tail_periods=args.tail_periods,
        steps_per_period=args.steps_per_period,
        samples_per_rotation=args.samples_per_rotation,
        initial_x_perturbation=args.initial_x_perturbation,
        params=params,
        progress_every=100,
    )
    spline = audit.build_state_spline(tail)
    metric = np.asarray(tail.metric, dtype=float)
    gram_error = float(np.linalg.norm(basis.T @ metric @ basis - np.eye(9), ord="fro"))

    inverse, inverse_box = base.mp_inverse_enclosure(basis)
    basis_box = base.constant_matrix_box(basis)
    inverse_identity_error = float(np.linalg.norm(inverse @ basis - np.eye(9), ord="fro"))

    domain_left = start
    domain_right = start + max(lengths.values())
    kappa0 = (55.0 / 6.0) * (10.0 / args.q)
    envelope = LocalCubicGeneratorEnvelope(
        base,
        audit,
        spline,
        np.asarray(tail.s, dtype=float),
        domain_left=domain_left,
        domain_right=domain_right,
        kappa0=kappa0,
        params=params,
        basis=basis,
        basis_box=basis_box,
        left_matrix=inverse,
        left_box=inverse_box,
    )

    # Point containment checks on the exact local boxes.
    point_containment = True
    point_width_maximum = 0.0
    for value in np.linspace(domain_left, domain_right, 17):
        point = envelope.point(float(value))
        box = envelope.box(float(value), float(value))
        point_containment = point_containment and base.box_contains(box, point)
        point_width_maximum = max(point_width_maximum, box_width_max(box))
    if not point_containment:
        raise AssertionError("Point generator escaped exact micro-box enclosure")

    transports: dict[str, LocalValidatedTransport] = {}
    transport_starts = {
        "line": start,
        "second": start + p_line,
        "oriented": start,
        "two_line": start,
    }
    for name in ("line", "second", "oriented", "two_line"):
        print(f"  validating {name}", flush=True)
        transports[name] = validate_transport_relative_defect(
            base,
            envelope,
            start=transport_starts[name],
            step=common_step,
            steps=step_counts[name],
            residual_subdivisions=args.residual_subdivisions,
            label=name,
        )
        print(
            f"  {name} done: radius={transports[name].radius:.6e}, "
            f"archived discrepancy={relative_matrix_difference(transports[name].center, archived[name]):.3e}",
            flush=True,
        )

    structural = base.structural_bounds(
        transports["line"].center,
        transports["line"].radius,
        transports["second"].center,
        transports["second"].radius,
        transports["oriented"].center,
        transports["oriented"].radius,
        transports["two_line"].center,
        transports["two_line"].radius,
        z_index=z_index,
        tau=args.planar_failure_threshold,
    )

    rows: dict[str, Any] = {}
    for name, result in transports.items():
        rows[name] = {
            "steps": result.steps,
            "radius": result.radius,
            "archived_relative_discrepancy": relative_matrix_difference(
                result.center, archived[name]
            ),
            "maximum_microbox_width": result.maximum_microbox_width,
            "maximum_path_distance_from_identity": result.maximum_path_distance_from_identity,
            "maximum_relative_defect_rate": result.maximum_relative_defect_rate,
            "accumulated_relative_defect": result.accumulated_relative_defect,
            "maximum_local_relative_error": result.maximum_local_relative_error,
            "maximum_local_absolute_radius": result.maximum_local_absolute_radius,
            "microbox_cache_size": result.microbox_cache_size,
        }

    endpoint_radius_sum = transports["oriented"].radius + transports["two_line"].radius
    pilot_target_passed = bool(
        transports["oriented"].radius <= args.target_radius
        and transports["two_line"].radius <= args.target_radius
        and structural["all_structural_pass"]
    )
    if pilot_target_passed:
        classification = (
            "RELATIVE-DEFECT MICRO-BOX PILOT PASSED: at the selected start, the "
            "moving-frame validation preserves all four structural statements "
            "with both long-endpoint radii below the requested target."
        )
    elif structural["all_structural_pass"]:
        classification = (
            "STRUCTURAL PILOT PASSED, TARGET RADIUS NOT YET MET: the selected "
            "start is rigorously separated, but refinement is still useful before "
            "scaling to all dense starts."
        )
    else:
        classification = (
            "PILOT OPEN: exact micro-boxes and relative-defect validation improved "
            "the architecture but do not yet preserve every structural margin at "
            "the selected start."
        )

    payload: dict[str, Any] = {
        "script_version": SCRIPT_VERSION,
        "scope": "one-start validated frozen cubic-spline linear cocycle; nonlinear orbit cache not yet validated",
        "dense_raw": str(args.dense_raw),
        "dense_raw_sha256": sha256(args.dense_raw),
        "orbit": str(args.orbit),
        "orbit_sha256": sha256(args.orbit),
        "q": args.q,
        "center_index": args.center_index,
        "start": start,
        "p_line": p_line,
        "p_oriented": p_oriented,
        "common_step": common_step,
        "steps_per_line": args.steps_per_line,
        "step_counts": step_counts,
        "residual_subdivisions": args.residual_subdivisions,
        "mp_dps": args.mp_dps,
        "basis_gram_error": gram_error,
        "basis_inverse_identity_error": inverse_identity_error,
        "point_generator_containment_passed": point_containment,
        "point_generator_interval_width_maximum": point_width_maximum,
        "target_radius": args.target_radius,
        "endpoint_radius_sum": endpoint_radius_sum,
        "transports": rows,
        "structural": {
            key: (bool(value) if isinstance(value, (bool, np.bool_)) else float(value))
            for key, value in structural.items()
        },
        "pilot_target_passed": pilot_target_passed,
        "classification": classification,
    }

    prefix = args.output_prefix
    prefix.parent.mkdir(parents=True, exist_ok=True)
    report_path = prefix.with_name(prefix.name + "_report.txt")
    json_path = prefix.with_suffix(".json")
    raw_path = prefix.with_name(prefix.name + "_raw.npz")
    write_report(report_path, payload)
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    np.savez_compressed(
        raw_path,
        script_version=np.asarray(SCRIPT_VERSION),
        center_index=np.asarray(args.center_index),
        start=np.asarray(start),
        p_line=np.asarray(p_line),
        p_oriented=np.asarray(p_oriented),
        common_step=np.asarray(common_step),
        basis=basis,
        basis_labels=np.asarray(labels, dtype=object),
        line_center=transports["line"].center,
        line_radius=np.asarray(transports["line"].radius),
        second_center=transports["second"].center,
        second_radius=np.asarray(transports["second"].radius),
        oriented_center=transports["oriented"].center,
        oriented_radius=np.asarray(transports["oriented"].radius),
        two_line_center=transports["two_line"].center,
        two_line_radius=np.asarray(transports["two_line"].radius),
    )

    print("=" * 78)
    print(report_path.read_text(), end="")
    print(f"report = {report_path.resolve()}")
    print(f"JSON   = {json_path.resolve()}")
    print(f"raw    = {raw_path.resolve()}")


if __name__ == "__main__":
    main()
