#!/usr/bin/env python3
"""Validated start-coordinate bridge pilot for the Q=550 frozen-spline cocycle.

This script starts from the rigorously validated m=192 transport balls at dense
center 67 and propagates them across neighboring start-coordinate cells using

    dT/ds = B(s+b) T - T B(s+a),

with (a,b) chosen for line, second, oriented, and 2P_line transports.

The archived dense matrices are used only as a Hermite guide curve.  A rigorous
residual enclosure plus a logarithmic-norm bound transports the certified ball
from cell to cell.  The default run is a local pilot over four cells on each
side; use --cells-each-side 80 only after the pilot margins are satisfactory.

Scope remains the linear cocycle generated by the frozen natural cubic spline.
The nonlinear orbit cache is not yet validated against an exact trajectory.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

import mpmath as mp
import numpy as np

SCRIPT_VERSION = "2026-08-06-q550-start-coordinate-bridge-pilot-v1.1"
DEFAULT_BASE = Path("test_support_q550_interval_spline_cocycle_proof.py")
DEFAULT_PILOT = Path("test_support_q550_relative_defect_microbox_pilot_v1_3.py")
DEFAULT_DENSE = Path("support_q550_dense_start_span_closure_raw.npz")
DEFAULT_SEED = Path("support_q550_relative_defect_microbox_pilot_m192_raw.npz")
DEFAULT_AUDIT = Path("test_support_mobius_monodromy_audit.py")
DEFAULT_ORBIT = Path("support_feedback_q_curtain_cache/q_550_orbit.npz")
DEFAULT_OUTPUT = Path("support_q550_start_coordinate_bridge_pilot")


@dataclass
class BridgeResult:
    name: str
    seed_index: int
    first_index: int
    last_index: int
    node_radii: np.ndarray
    cell_residual_max: np.ndarray
    cell_mu_max: np.ndarray
    cell_growth: np.ndarray
    maximum_radius: float
    maximum_residual: float
    maximum_mu: float


def load_module(path: Path, name: str) -> ModuleType:
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def outward(value: float) -> float:
    return float(np.nextafter(float(value), np.inf))


def box_width_max(box: Any) -> float:
    return float(np.max(np.asarray(box.hi) - np.asarray(box.lo)))


def interval_symmetric_log_norm_gershgorin(box: Any, sign: float = 1.0) -> float:
    """Rigorous Gershgorin upper bound for mu_2(sign*A), A in box."""
    lo = np.asarray(box.lo, dtype=float)
    hi = np.asarray(box.hi, dtype=float)
    if sign < 0.0:
        lo, hi = -hi, -lo
    slo = np.nextafter(0.5 * (lo + lo.T), -np.inf)
    shi = np.nextafter(0.5 * (hi + hi.T), np.inf)
    n = lo.shape[0]
    bounds = []
    for i in range(n):
        radius = 0.0
        for j in range(n):
            if i == j:
                continue
            radius = outward(radius + max(abs(float(slo[i, j])), abs(float(shi[i, j]))))
        bounds.append(outward(float(shi[i, i]) + radius))
    return max(bounds)


def exp_upper(base: ModuleType, value: float) -> float:
    return float(base.exp_upper(float(value)))


def phi_signed_upper(base: ModuleType, rate: float, step: float) -> float:
    with mp.workdps(base.MP_DPS):
        r = mp.mpf(rate)
        h = mp.mpf(step)
        if abs(r) < mp.mpf("1e-30"):
            val = h
        else:
            val = mp.expm1(r * h) / r
        _, high = base.mp_bracket(val, ulps=4)
    return float(high)


def hermite_coefficients(y0: np.ndarray, y1: np.ndarray, f0: np.ndarray, f1: np.ndarray, h: float) -> list[np.ndarray]:
    a0 = y0
    a1 = h * f0
    a2 = -3.0 * y0 - 2.0 * h * f0 + 3.0 * y1 - h * f1
    a3 = 2.0 * y0 + h * f0 - 2.0 * y1 + h * f1
    return [a0, a1, a2, a3]


def centered_start_residual_box(
    base: ModuleType,
    coefficients: list[np.ndarray],
    h: float,
    end_box: Any,
    start_box: Any,
    end_mid: np.ndarray,
    start_mid: np.ndarray,
    path_box: Any,
    tau_left: float,
    tau_right: float,
    direction: float,
) -> Any:
    a0, a1, a2, a3 = coefficients
    residual_coefficients = [
        a1 / h - direction * (end_mid @ a0 - a0 @ start_mid),
        2.0 * a2 / h - direction * (end_mid @ a1 - a1 @ start_mid),
        3.0 * a3 / h - direction * (end_mid @ a2 - a2 @ start_mid),
        -direction * (end_mid @ a3 - a3 @ start_mid),
    ]
    tau = base.Box(np.asarray(float(tau_left)), np.asarray(float(tau_right)))
    frozen = base.polynomial_box(residual_coefficients, tau)
    delta_end = base.isub(end_box, base.exact_box(end_mid))
    delta_start = base.isub(start_box, base.exact_box(start_mid))
    variation = base.isub(
        base.imatmul(delta_end, path_box),
        base.imatmul(path_box, delta_start),
    )
    return base.isub(frozen, base.iscale(variation, direction))


def endpoint_derivative(envelope: Any, matrix: np.ndarray, s: float, shift_start: float, shift_end: float) -> np.ndarray:
    b0 = envelope.point(s + shift_start)
    b1 = envelope.point(s + shift_end)
    return b1 @ matrix - matrix @ b0


def propagate_cell(
    base: ModuleType,
    pilot: ModuleType,
    envelope: Any,
    *,
    s_from: float,
    s_to: float,
    y_from: np.ndarray,
    y_to: np.ndarray,
    dy_from_ds: np.ndarray,
    dy_to_ds: np.ndarray,
    radius_in: float,
    shift_start: float,
    shift_end: float,
    subdivisions: int,
) -> tuple[float, float, float, float, float]:
    direction = 1.0 if s_to > s_from else -1.0
    h = abs(s_to - s_from)
    f0 = direction * dy_from_ds
    f1 = direction * dy_to_ds
    coeffs = hermite_coefficients(y_from, y_to, f0, f1, h)

    radius = float(radius_in)
    residual_max = 0.0
    mu_max = -math.inf
    generator_width_max = 0.0

    for k in range(subdivisions):
        tl = k / subdivisions
        tr = (k + 1) / subdivisions
        tm = 0.5 * (tl + tr)
        u_left = tl * h
        u_right = tr * h
        s_left = s_from + direction * u_left
        s_right = s_from + direction * u_right
        physical_left = min(s_left, s_right)
        physical_right = max(s_left, s_right)

        end_box = envelope.box(physical_left + shift_end, physical_right + shift_end)
        start_box = envelope.box(physical_left + shift_start, physical_right + shift_start)
        smid = s_from + direction * (tm * h)
        end_mid = envelope.point(smid + shift_end)
        start_mid = envelope.point(smid + shift_start)

        path_box = pilot.hermite_path_box(
            base, y_from, y_to, f0, f1, h, tau_left=tl, tau_right=tr
        )
        residual_box = centered_start_residual_box(
            base, coeffs, h, end_box, start_box, end_mid, start_mid,
            path_box, tl, tr, direction,
        )
        residual = float(base.box_frobenius_upper(residual_box))

        mu = (
            interval_symmetric_log_norm_gershgorin(end_box, sign=direction)
            + interval_symmetric_log_norm_gershgorin(start_box, sign=-direction)
        )
        du = h / subdivisions
        growth = exp_upper(base, mu * du)
        forcing = phi_signed_upper(base, mu, du)
        radius = outward(growth * radius + forcing * residual)

        residual_max = max(residual_max, residual)
        mu_max = max(mu_max, mu)
        generator_width_max = max(generator_width_max, box_width_max(end_box), box_width_max(start_box))

    return radius, residual_max, mu_max, exp_upper(base, mu_max * h), generator_width_max


def validate_transport_bridge(
    base: ModuleType,
    pilot: ModuleType,
    envelope: Any,
    *,
    name: str,
    starts: np.ndarray,
    matrices: np.ndarray,
    seed_index: int,
    seed_center: np.ndarray,
    seed_radius: float,
    shift_start: float,
    shift_end: float,
    cells_each_side: int,
    subdivisions: int,
) -> BridgeResult:
    centers = np.asarray(matrices, dtype=float).copy()
    centers[seed_index] = np.asarray(seed_center, dtype=float)
    derivatives = np.asarray([
        endpoint_derivative(envelope, centers[i], float(starts[i]), shift_start, shift_end)
        for i in range(starts.size)
    ])

    first = max(0, seed_index - cells_each_side)
    last = min(starts.size - 1, seed_index + cells_each_side)
    radii = np.full(starts.size, np.nan)
    radii[seed_index] = seed_radius
    cell_residual = np.full(starts.size - 1, np.nan)
    cell_mu = np.full(starts.size - 1, np.nan)
    cell_growth = np.full(starts.size - 1, np.nan)

    print(f"  {name}: seed radius={seed_radius:.6e}, nodes [{first},{last}]", flush=True)

    for i in range(seed_index, last):
        out = propagate_cell(
            base, pilot, envelope,
            s_from=float(starts[i]), s_to=float(starts[i+1]),
            y_from=centers[i], y_to=centers[i+1],
            dy_from_ds=derivatives[i], dy_to_ds=derivatives[i+1],
            radius_in=float(radii[i]), shift_start=shift_start, shift_end=shift_end,
            subdivisions=subdivisions,
        )
        radii[i+1], cell_residual[i], cell_mu[i], cell_growth[i], width = out
        print(f"    forward {i:>2}->{i+1:<2} radius={radii[i+1]:.3e} residual={cell_residual[i]:.3e} mu={cell_mu[i]:+.3e} width={width:.3e}", flush=True)

    for i in range(seed_index, first, -1):
        out = propagate_cell(
            base, pilot, envelope,
            s_from=float(starts[i]), s_to=float(starts[i-1]),
            y_from=centers[i], y_to=centers[i-1],
            dy_from_ds=derivatives[i], dy_to_ds=derivatives[i-1],
            radius_in=float(radii[i]), shift_start=shift_start, shift_end=shift_end,
            subdivisions=subdivisions,
        )
        radii[i-1], cell_residual[i-1], cell_mu[i-1], cell_growth[i-1], width = out
        print(f"    backward {i:>2}->{i-1:<2} radius={radii[i-1]:.3e} residual={cell_residual[i-1]:.3e} mu={cell_mu[i-1]:+.3e} width={width:.3e}", flush=True)

    active_radii = radii[first:last+1]
    active_residual = cell_residual[first:last]
    active_mu = cell_mu[first:last]
    return BridgeResult(
        name=name,
        seed_index=seed_index,
        first_index=first,
        last_index=last,
        node_radii=radii,
        cell_residual_max=cell_residual,
        cell_mu_max=cell_mu,
        cell_growth=cell_growth,
        maximum_radius=float(np.nanmax(active_radii)),
        maximum_residual=float(np.nanmax(active_residual)) if active_residual.size else 0.0,
        maximum_mu=float(np.nanmax(active_mu)) if active_mu.size else 0.0,
    )


def structural_at_nodes(base: ModuleType, dense: dict[str, np.ndarray], results: dict[str, BridgeResult], z_index: int, tau: float, first: int, last: int) -> list[dict[str, Any]]:
    rows = []
    for i in range(first, last + 1):
        s = base.structural_bounds(
            dense["line"][i], float(results["line"].node_radii[i]),
            dense["second"][i], float(results["second"].node_radii[i]),
            dense["oriented"][i], float(results["oriented"].node_radii[i]),
            dense["two_line"][i], float(results["two_line"].node_radii[i]),
            z_index=z_index, tau=tau,
        )
        rows.append({"index": i, **s})
    return rows


def self_test(base: ModuleType, pilot: ModuleType) -> None:
    from scipy.linalg import expm
    rng = np.random.default_rng(20260806)
    raw = rng.normal(size=(9, 9))
    b = 0.5 * (raw - raw.T) / max(np.linalg.norm(raw - raw.T, ord=2), 1e-15) - 0.02*np.eye(9)

    class Env:
        def point(self, s: float) -> np.ndarray:
            del s
            return b
        def box(self, a: float, c: float) -> Any:
            del a, c
            return base.float_box(b, ulps=6)

    starts = np.linspace(-0.04, 0.04, 9)
    y0 = rng.normal(size=(9,9))
    mats = np.asarray([expm(b*s) @ y0 @ expm(-b*s) for s in starts])
    seed = 4
    result = validate_transport_bridge(
        base, pilot, Env(), name="self", starts=starts, matrices=mats,
        seed_index=seed, seed_center=mats[seed], seed_radius=1e-12,
        shift_start=0.0, shift_end=0.3, cells_each_side=4, subdivisions=8,
    )
    if not np.nanmax(result.node_radii) < 1e-6:
        raise AssertionError(f"self-test radius too large: {np.nanmax(result.node_radii):.3e}")
    print("start-coordinate bridge self-test passed", flush=True)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--base-script", type=Path, default=DEFAULT_BASE)
    p.add_argument("--pilot-script", type=Path, default=DEFAULT_PILOT)
    p.add_argument("--dense-raw", type=Path, default=DEFAULT_DENSE)
    p.add_argument("--seed-raw", type=Path, default=DEFAULT_SEED)
    p.add_argument("--audit-script", type=Path, default=DEFAULT_AUDIT)
    p.add_argument("--orbit", type=Path, default=DEFAULT_ORBIT)
    p.add_argument("--q", type=float, default=550.0)
    p.add_argument("--cells-each-side", type=int, default=4)
    p.add_argument("--cell-subdivisions", type=int, default=32)
    p.add_argument("--mp-dps", type=int, default=80)
    p.add_argument("--tail-periods", type=int, default=70)
    p.add_argument("--steps-per-period", type=int, default=160)
    p.add_argument("--samples-per-rotation", type=int, default=720)
    p.add_argument("--initial-x-perturbation", type=float, default=1e-6)
    p.add_argument("--gamma-rho", type=float, default=0.3)
    p.add_argument("--tau", type=float, default=0.95)
    p.add_argument("--output-prefix", type=Path, default=DEFAULT_OUTPUT)
    p.add_argument("--self-test", action="store_true")
    args = p.parse_args()

    base = load_module(args.base_script, "bridge_base")
    base.MP_DPS = args.mp_dps
    pilot = load_module(args.pilot_script, "bridge_pilot")
    if args.self_test:
        self_test(base, pilot)
        return

    audit = load_module(args.audit_script, "bridge_audit")
    with np.load(args.dense_raw, allow_pickle=True) as d, np.load(args.seed_raw, allow_pickle=True) as seed:
        starts = np.asarray(d["starts"], dtype=float)
        basis = np.asarray(d["basis"], dtype=float)
        labels = [str(x) for x in d["basis_labels"]]
        p_line = float(d["p_line"])
        p_oriented = float(d["p_oriented"])
        dense = {name: np.asarray(d[f"fine_{name}"], dtype=float) for name in ("line","second","oriented","two_line")}
        seed_index = int(seed["center_index"])
        seed_centers = {name: np.asarray(seed[f"{name}_center"], dtype=float) for name in dense}
        seed_radii = {name: float(seed[f"{name}_radius"]) for name in dense}

    params = audit.ModelParameters(gamma_rho=args.gamma_rho)
    orbit = audit.load_orbit(args.q, args.orbit)
    tail = audit.collect_uniform_tail(
        orbit, tail_periods=args.tail_periods, steps_per_period=args.steps_per_period,
        samples_per_rotation=args.samples_per_rotation,
        initial_x_perturbation=args.initial_x_perturbation,
        params=params, progress_every=100,
    )
    spline = audit.build_state_spline(tail)
    metric = np.asarray(tail.metric, dtype=float)
    inverse, inverse_box = base.mp_inverse_enclosure(basis)
    basis_box = base.constant_matrix_box(basis)
    domain_left = float(starts[0])
    domain_right = float(starts[-1] + max(p_oriented, 2*p_line))
    kappa0 = (55.0/6.0)*(10.0/args.q)
    envelope = pilot.LocalCubicGeneratorEnvelope(
        base, audit, spline, np.asarray(tail.s, dtype=float),
        domain_left=domain_left, domain_right=domain_right,
        kappa0=kappa0, params=params, basis=basis, basis_box=basis_box,
        left_matrix=inverse, left_box=inverse_box,
    )

    shifts = {
        "line": (0.0, p_line),
        "second": (p_line, p_oriented),
        "oriented": (0.0, p_oriented),
        "two_line": (0.0, 2.0*p_line),
    }
    print(f"Script version       = {SCRIPT_VERSION}")
    print(f"seed center          = {seed_index}/{starts.size-1}")
    print(f"cells each side      = {args.cells_each_side}")
    print(f"cell subdivisions    = {args.cell_subdivisions}")
    print(f"dense gap            = {starts[1]-starts[0]:.15e}")

    results = {}
    for name in ("line","second","oriented","two_line"):
        a,b = shifts[name]
        results[name] = validate_transport_bridge(
            base, pilot, envelope, name=name, starts=starts, matrices=dense[name],
            seed_index=seed_index, seed_center=seed_centers[name], seed_radius=seed_radii[name],
            shift_start=a, shift_end=b, cells_each_side=args.cells_each_side,
            subdivisions=args.cell_subdivisions,
        )

    first = max(0, seed_index-args.cells_each_side)
    last = min(starts.size-1, seed_index+args.cells_each_side)
    z_index = labels.index("upper z residual")
    dense_structural = {name: values.copy() for name, values in dense.items()}
    for name in dense_structural:
        dense_structural[name][seed_index] = seed_centers[name]
    rows = structural_at_nodes(base, dense_structural, results, z_index, args.tau, first, last)
    all_pass = all(bool(r["all_structural_pass"]) for r in rows)

    payload = {
        "script_version": SCRIPT_VERSION,
        "q": args.q,
        "seed_index": seed_index,
        "first_index": first,
        "last_index": last,
        "cells_each_side": args.cells_each_side,
        "cell_subdivisions": args.cell_subdivisions,
        "basis_gram_error": float(np.linalg.norm(basis.T@metric@basis-np.eye(9), ord="fro")),
        "all_structural_nodes_passed": all_pass,
        "transport_maximum_radii": {k:v.maximum_radius for k,v in results.items()},
        "transport_maximum_residuals": {k:v.maximum_residual for k,v in results.items()},
        "transport_maximum_mu": {k:v.maximum_mu for k,v in results.items()},
        "node_structural": rows,
        "classification": (
            "START-COORDINATE BRIDGE PILOT PASSED" if all_pass else
            "START-COORDINATE BRIDGE PILOT OPEN"
        ),
    }
    prefix=args.output_prefix
    prefix.parent.mkdir(parents=True, exist_ok=True)
    json_path=prefix.with_suffix(".json")
    report_path=prefix.with_name(prefix.name+"_report.txt")
    raw_path=prefix.with_name(prefix.name+"_raw.npz")
    json_path.write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n")
    lines=[
        f"Script version: {SCRIPT_VERSION}","",
        "Q=550 START-COORDINATE BRIDGE PILOT","=======================================","",
        f"seed index                         = {seed_index}",
        f"validated node range               = [{first},{last}]",
        f"cell subdivisions                  = {args.cell_subdivisions}",
        f"all structural nodes passed        = {all_pass}","",
    ]
    for name,r in results.items():
        lines += [
            name,
            f"  maximum propagated radius        = {r.maximum_radius:.12e}",
            f"  maximum cell residual            = {r.maximum_residual:.12e}",
            f"  maximum logarithmic norm bound   = {r.maximum_mu:+.12e}",
        ]
    lines += ["", "Node structural decisions"]
    for row in rows:
        lines.append(
            f"  index={row['index']:>2} active={row['active_orientation_pass']} "
            f"without_z={row['without_z_orientation_pass']} mediation={row['mediation_pass']} "
            f"endpoint={row['endpoint_separation_pass']} all={row['all_structural_pass']}"
        )
    lines += ["",f"classification = {payload['classification']}","",
              "Scope: validated propagation for the frozen-spline linear cocycle only."]
    report_path.write_text("\n".join(lines)+"\n")
    np.savez_compressed(
        raw_path, starts=starts, first_index=first, last_index=last,
        **{f"{k}_node_radii":v.node_radii for k,v in results.items()},
        **{f"{k}_cell_residual":v.cell_residual_max for k,v in results.items()},
        **{f"{k}_cell_mu":v.cell_mu_max for k,v in results.items()},
    )
    print("="*78)
    print("\n".join(lines))
    print(f"report = {report_path.resolve()}")
    print(f"JSON   = {json_path.resolve()}")
    print(f"raw    = {raw_path.resolve()}")


if __name__ == "__main__":
    main()
